### PR TITLE
Handle text-based responses

### PR DESCRIPTION
**Pull request by OldhamMade**
Added ability to handle text-based responses. `article_html`, `title`, and `authors` attributes are not parsed or populated. Updated to handle content types with `charset`.

### CODE REVIEW

**Comment by keepcosmos** [comment]
@Thanks for PR, could you rebase commits?

**Comment by edevil** [comment]
@OldhamMade ping

**Comment by OldhamMade** [comment]
@keepcosmos was a squash what you were looking for?

**Comment by keepcosmos** [comment]
@OldhamMade Yes, please squash for clean commit :)

**Comment by OldhamMade** [comment]
OK, commits squashed, tests passed. HTH!

**Comment by keepcosmos** [comment]
Thank! 👍 I just released v 0.9

**Pull request merged**
