### PR TITLE
Fix Issue 65: incorrect node return format for doctype when using html5ever

### PR DESCRIPTION
**Pull request by vkryukov**

### CODE REVIEW

**Comment by vkryukov** [comment]
The failing tests for Elixir 1.10 is because `html5ever` requires a newer Elixir version.

**Comment by Valian** [comment]
@vkryukov any suggestion how to solve it? We could install html5ever conditionally only on newer node versions and include test only if it's installed?

**Comment by vkryukov** [comment]
I did a few changes to make the test suite happy:

1. Make dependency on `html5ever` conditional on the version number be >= 1.13
2. Run tests in `test/readability_test.exs` run sequentially.

The first is a no regret move, the second is a hackery that I don't like, but we have to use it because there is no other way (currently) to pass html parser information to Floki other than through a global variable.

For the future 1.0 rewrite, we need to allow setting Floki parser individually in each readability call.

**Comment by vkryukov** [comment]
Also, looks like `Floki` is behaving as documented, since `html_doctype` is  valid `html_node` subtype: https://hexdocs.pm/floki/Floki.html#t:html_doctype/0, so the fix is indeed needed.

**Comment by Valian** [comment]
Merged! Thank you!

**Pull request merged**
